import React from "react";
import HorizontalTextAnimation from "../components/HorizontalTextAnimation";

const Banner = () => {
  return (
    <div>
      <HorizontalTextAnimation
        text="WEB DESIGN — INTERFACES — UI/UX — SITE WEB — LOGO — BRANDING — VISUAL
          IDENTITY — APP DESIGN — MOBILE DESIGN — GRAPHIC DESIGN — TYPOGRAPHY — PRODUCT DESIGN — ANIMATION — DIGITAL MARKETING — RESPONSIVE DESIGN — PRINT DESIGN — ILLUSTRATION — WEB DEVELOPMENT — USER RESEARCH — PROTOTYPE DESIGN — CONTENT STRATEGY — SOCIAL MEDIA DESIGN — SEARCH ENGINE OPTIMIZATION — CUSTOMER EXPERIENCE — LANDING PAGE DESIGN — MARKETING STRATEGY — INFORMATION ARCHITECTURE — USER TESTING — E-COMMERCE DESIGN — DIGITAL STRATEGY — USER PERSONAS — WIREFRAMING"
      />
    </div>
  );
};

export default Banner;
